version: '3.7'
services:
  web:
    build: .
    command: gunicorn pse.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code/
      - static_volume:/code/static
    ports:
      - "8000:8000"
    env_file:
      - ./env
    depends_on:
      - db
    links:
      - elasticsearch:elasticsearch
      - rabbitmq:rabbitmq
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pse_db_user
      - POSTGRES_PASSWORD=pse_db_password
      - POSTGRES_DB=pse_db
  elasticsearch:
    image: elasticsearch:6.6.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery worker -A pse.celery.app -Q default -n default@%h
    volumes:
      - .:/code/
    depends_on:
      - web
      - rabbitmq
volumes:
  postgres_data:
  static_volume:
  esdata:
