version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.7-alpine
    command: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    volumes:
      - ./data:/var/lib/rabbitmq:rw
      - ./definitions.json:/opt/definitions.json:ro
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
  elasticsearch:
    image: elasticsearch:7.4.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  web:
    build: .
    command: sh -c "service cron start && gunicorn pse.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code/
      - static_volume:/code/static
    ports:
      - "8000:8000"
    env_file:
      - ./env
    depends_on:
      - db
      - rabbitmq
      - worker
    links:
      - elasticsearch:elasticsearch
      - rabbitmq:rabbitmq
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pse_db_user
      - POSTGRES_PASSWORD=pse_db_password
      - POSTGRES_DB=pse_db
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A pse worker --loglevel=info
    volumes:
      - .:/code/
    env_file:
      - ./env
    depends_on:
      - rabbitmq
      - db
    links:
      - rabbitmq
      - db
volumes:
  postgres_data:
  static_volume:
  esdata:
