# Generated by Django 2.2.7 on 2019-11-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Tytuł pakietu')),
                ('author', models.CharField(max_length=250, verbose_name='Autor')),
                ('description', models.TextField(verbose_name='Opis pakietu')),
                ('keywords', models.CharField(blank=True, max_length=250, null=True, verbose_name='Słowa kluczowe')),
                ('version', models.CharField(max_length=50, verbose_name='Bieżąca wersja')),
                ('url', models.URLField(unique=True, verbose_name='Url do projektu')),
            ],
        ),
    ]
