# Generated by Django 2.2.7 on 2019-11-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='author_email',
            field=models.EmailField(blank=True, max_length=70, null=True, verbose_name='Email autora'),
        ),
    ]
